### ISSUE TITLE
 Support GNOME 45 (moved to ESM)

### ISSUE THREAD

**Issue by 7system7** [PRATAP-KUMAR/app-menu-icon#1]
### Information

- **Operating System**:  
```
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```
- **Gnome Shell Version**: 45.0
- **Xorg/Wayland?**: Wayland

### What is the current behavior?

The extension is not working 'cause the [GNOME moved to ESM](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm). 😢 But we are waiting for this extension, because it is sooo awesome.

### Steps to reproduce the problem

1. Install the extension.
2. It won't work because

```js
SyntaxError: import declarations may only appear at top level of a module
```

### What is the expected behavior?

To work.

**Comment by pratap-panabaka** [comment]
Hi, The AppMenu is removed in Gnome 45. Can you share screenshot of this AppMenu from gnome-shell v45 please.

Thanks

**Comment by 7system7** [comment]
Oh, lol. I did not read all changes before that. I am sorry!

Then, let's pretend I didn't write it. 😃
